export let
  { PI, floor, abs, sign, sin, cos, max, min, random, hypot } = Math,
  l = localStorage,
  doc = document,
  Pixel=2,
  rand = a => random() * a,
  randInt = a => rand(a) | 0,
  range=(a=1000)=>rand(a)-rand(a),
  normDeg = a => ((a % 360) + 360) % 360,
  AB=a=>abs(a),
  resetXY = (x, y) => ({ x, y }),
  resetXYWH = ([x, y, w, h]) => ({ x, y, w, h }),
  floorSet = ({ x, y }) => resetXY(floor(x), floor(y)),
  M=(a,b)=>max(a,b),
  N=(a,b)=>min(a,b),
  hyb = (a, b) => hypot(a.x - b.x, a.y - b.y),
  add = (a, b) => resetXY(a.x + b.x, a.y + b.y),
  substract = (a, b) => resetXY(a.x - b.x, a.y - b.y),
  dot = (a, b) => resetXY(a.x * b, a.y * b),
  comp = (a, b) => a.x == b.x && a.y == b.y,
  HIT=(a,b,m=0)=>a.x < b.x + b.w + m && a.x + a.w > b.x - m && a.y < b.y + b.h + m && a.y + a.h > b.y - m,
  boxesTouch = (a, b, m = 3) => HIT(a, b, m),
  CB = b => ({ x: b.x - b.w / 2, y: b.y - b.h / 2, w: b.w, h: b.h }),
  us=a=>a.toUpperCase(),
  localSet = (a, b) => l.setItem(a, JSON.stringify(b)),
  localGet = a => l.getItem(a),
  pA=(a,b)=>a.push(b)
  ;