import { localSet, N, rand,  range,  resetXY, resetXYWH } from "./basic";
import { createPlayer, gameState, getCurrentCharacter, InitUpside, resetPlayer, toggleUpside } from "./core";
export const LEVEL_DEFS = [
    {
    "name": 1,
    "spawn": [
        20,
        20
    ],
    "characterQueue": [
        2,
        3,
        4,
        5
    ],
    "platforms": [
        [
            0,
            60,
            400,
            40
        ],
        [
            300,
            -60,
            40,
            120,
        ]
    ],
    "spikes": [
        [
            180,
            50,
            180,
            8,
            "u",
            1
        ]
    ],
    "switches": [
        [
            80,
            50,
            30,
            10,
            0,
            "PUSH [X] WAIT OR [X]PIN WALL",
            0,
            0
        ]
    ],
    "gates": [
        [
            150,
            -60,
            20,
            120,
            0,
            1,
            "EXIT"
        ]
    ],
    "exit": [
        360,
        0,
        30,
        60
    ]
},{
    "name": 2,
    "spawn": [
        20,
        20
    ],
    "characterQueue": [
        2,
        3,
        4,
    ],
    "platforms": [
        [
            0,
            60,
            400,
            40
        ],
        [
            150,
            -40,
            90,
            30
        ],
        [
            230,
            -90,
            20,
            80
        ]
    ],
    "spikes": [
        [
            152,
            -50,
            70,
            10,
            "u",
            0
        ]
    ],
    "switches": [
        [
            170,
            -50,
            30,
            10,
            0,
            "EXIT",
            0,
            0
        ],
        [
            88,
            48,
            30,
            10,
            1,
            "PUSH [C] LEAVE SOUL",
            1,
            0
        ]
    ],
    "gates": [
        [
            320,
            -90,
            20,
            150,
            0,
            1,
            "EXIT"
        ],
        [
            130,
            -90,
            20,
            150,
            1,
            0,
            ""
        ]
    ],
    "exit": [
        360,
        0,
        30,
        60
    ]
},
{
    "name": 3,
    "spawn": [
        0,
        0
    ],
    "characterQueue": [
        0,
        2,
        3,
        0
    ],
    "platforms": [
        [
            0,
            16,
            350,
            30
        ]
    ],
    "switches": [
        [
            160,
            8,
            40,
            8,
            0,
            "EXIT",
            0,
            0
        ]
    ],
    "gates": [
        [
            280,
            -110,
            20,
            130,
            0,
            1,
            "EXIT"
        ]
    ],
    "mirrors": [
        [
            50,
            -30,
            30,
            40,
            1,
            0
        ]
    ],
    "monsters": [
        [
            210,
            -30,
            3,
            0,
            0,
            300
        ],[
            150,
            -30,
            3,
            2,
            0,
            300
        ]
    ],
    "exit": [
        320,
        -40,
        32,
        60
    ]
},
   {
    "name": 4,
    "spawn": [
        120,
        -50
    ],
    "characterQueue": [
        2,
        3,
        4,
        5,
        6,
        6,
        6,
        1,
        0,
        6,
        1
    ],
    "platforms": [
        [
            -100,
            0,
            780,
            40
        ],
        [
            480,
            -230,
            50,
            230
        ],
        [
            530,
            -150,
            150,
            150
        ],
        [
            -100,
            -100,
            120,
            20
        ]
    ],
    "spikes": [
        [
            230,
            -8,
            250,
            8,
            "u",
            1
        ],
        [
            230,
            -8,
            250,
            8,
            "u",
            0
        ]
    ],
    "switches": [
        [
            -70,
            -8,
            40,
            10,
            1,
            "SOUL",
            0,
            0
        ],
        [
            70,
            -8,
            40,
            8,
            0,
            "EXIT",
            1,
            0
        ],
        [
            472,
            -136,
            10,
            60,
            0,
            "LIGHT",
            2,
            1
        ]
    ],
    "gates": [
        [
            296,
            -224,
            16,
            232,
            1,
            0,
            ""
        ],
        [
            460,
            -330,
            20,
            200,
            0,
            1,
            "EXIT"
        ],
        [
            0,
            -100,
            20,
            100,
            0,
            0,
            "LIGHT"
        ]
    ],
    "mirrors": [
        [
            -50,
            -140,
            30,
            50,
            1,
            0
        ]
    ],
    "monsters": [],
    "exit": [
        640,
        -210,
        30,
        60
    ]
},{
    "name": 5,
    "spawn": [
        160,
        -10
    ],
    "characterQueue": [
        2,
        3,
        4,
        5,
        6,
        0,
        1
    ],
    "platforms": [
        [
            0,
            150,
            500,
            40
        ],
        [
            340,
            0,
            160,
            30
        ],
        [
            200,
            80,
            88,
            10
        ],
        [
            0,
            0,
            120,
            40
        ]
    ],
    "spikes": [
        [
            200,
            90,
            80,
            10,
            "d",
            0
        ]
    ],
    "switches": [
        [
            450,
            140,
            30,
            10,
            0,
            "EXIT",
            0,
            0
        ],
        [
            30,
            -10,
            60,
            10,
            0,
            "",
            1,
            1
        ],
        [
            450,
            140,
            30,
            10,
            0,
            "EXIT",
            2,
            0
        ]
    ],
    "gates": [
        [
            400,
            30,
            10,
            120,
            0,
            1,
            "EXIT"
        ],
        [
            320,
            -300,
            10,
            450,
            0,
            0,
            "LIGHT"
        ],
        [
            400,
            -200,
            10,
            200,
            0,
            1,
            "EXIT"
        ],
         [
            350,
            30,
            10,
            120,
            1,
            0,
            ""
        ],
    ],
    "mirrors": [
        [
            50,
            110,
            24,
            40,
            1,
            0
        ],
        [
            230,
            30,
            30,
            40,
            2,
            45
        ],
        [
            280,
            -40,
            24,
            40,
            3,
            135
        ]
    ],
    "monsters": [
        [
            80,
            -40,
            1,
            0,
            0,
            90
        ],
        [
            400,
            -40,
            2,
            6,
            300,
            500
        ]
    ],
    "exit": [
        450,
        -50,
        30,
        50
    ]
},{
    "name": 6,
    "spawn": [
        90,
        580
    ],
    "characterQueue": [
        2,
        3,
        4,
        5,
        6,
        6,
        6,
        1,
        0,
        2,
        4,
        6,
        5,
        5,
        6
    ],
    "platforms": [
        [
            0,
            0,
            100,
            20
        ],
        [
            0,
            0,
            50,
            600
        ],
        [
            300,
            0,
            50,
            600
        ],
        [
            0,
            600,
            240,
            20
        ],
        [
            130,
            480,
            80,
            20
        ],
        [
            100,
            130,
            100,
            20
        ],
        [
            100,
            300,
            100,
            20
        ]
    ],
    "spikes": [
        [
            50,
            200,
            8,
            350,
            "r",
            0
        ],
        [
            290,
            0,
            8,
            200,
            "l",
            0
        ],
        [
            292,
            320,
            8,
            140,
            "l",
            1
        ]
    ],
    "switches": [
        [
            136,
            120,
            44,
            8,
            0,
            "EXIT",
            0,
            0
        ],
        [
            56,
            400,
            60,
            10,
            1,
            "[C] SOUL",
            1,
            0
        ],
        [
            100,
            290,
            40,
            10,
            1,
            "",
            2,
            0
        ]
    ],
    "gates": [
        [
            80,
            -200,
            20,
            200,
            0,
            1,
            "EXIT"
        ],
        [
            50,
            360,
            250,
            10,
            1,
            0,
            ""
        ],
        [
            50,
            200,
            250,
            8,
            1,
            0,
            ""
        ]
    ],
    "mirrors": [
        [
            160,
            560,
            24,
            40,
            1,
            0
        ],
        [
            260,
            560,
            30,
            40,
            3,
            23,
            265,
            300
        ],
        [
            250,
            200,
            24,
            40,
            3,
            125,
            240,
            300
        ],
        [
            250,
            0,
            24,
            40,
            3,
            125,
            250,
            300
        ]
    ],
    "monsters": [
        [
            120,
            80,
            3,
            6,
            100,
            200
        ],
        [
            140,
            260,
            2,
            4,
            100,
            200
        ]
    ],
    "exit": [
        24,
        -64,
        30,
        60
    ]
},{
    "name": 7,
    "spawn": [
        324,
        -20
    ],
    "characterQueue": [
        2,
        3,
        4,
        5,
        6,
        6,
        6,
        1,
        0,
        2,
        4,
        6,
        6,
        5,
        5,
        5
    ],
    "platforms": [
        [
            0,
            0,
            50,
            690
        ],
        [
            300,
            0,
            50,
            700
        ],
        [
            220,
            200,
            40,
            20
        ],
        [
            200,
            100,
            100,
            20
        ],
        [
            50,
            250,
            40,
            24
        ],
        [
            -100,
            750,
            200,
            30
        ],
        [
            50,
            150,
            50,
            16
        ],
        [
            240,
            300,
            20,
            20
        ],
        [
            200,
            400,
            30,
            20
        ],
        [
            80,
            350,
            40,
            20
        ],
        [
            60,
            550,
            30,
            16
        ],
        [
            200,
            600,
            100,
            20
        ]
    ],
    "spikes": [
        [
            -100,
            742,
            150,
            8,
            "u",
            1
        ],
        [
            -100,
            742,
            150,
            8,
            "u",
            0
        ],
        [
            200,
            92,
            100,
            8,
            "u",
            0
        ],
        [
            96,
            460,
            200,
            8,
            "u",
            0
        ],
        [
            50,
            680,
            110,
            8,
            "u",
            0
        ]
    ],
    "switches": [
        [
            240,
            90,
            40,
            8,
            0,
            "EXIT",
            0,
            0
        ],
        [
            56,
            240,
            20,
            10,
            1,
            "",
            1,
            0
        ],
        [
            240,
            290,
            20,
            10,
            0,
            "EXIT",
            2,
            0
        ],
        [
            90,
            340,
            20,
            10,
            1,
            "",
            3,
            0
        ]
    ],
    "gates": [
        [
            50,
            160,
            250,
            8,
            0,
            1,
            "EXIT"
        ],
        [
            50,
            200,
            250,
            10,
            1,
            0,
            ""
        ],
        [
            50,
            400,
            250,
            10,
            0,
            1,
            "EXIT"
        ],
        [
            50,
            450,
            250,
            8,
            1,
            0,
            ""
        ]
    ],
    "mirrors": [],
    "monsters": [
        [
            55,
            90,
            2,
            0,
            50,
            100
        ],
        [
            200,
            352,
            2,
            1,
            200,
            230
        ],
        [
            240,
            550,
            3,
            6,
            200,
            280
        ]
    ],
    "exit": [
        70,
        710,
        32,
        40
    ]
},
{
    "name": 8,
    "spawn": [
        70,
        20
    ],
    "characterQueue": [
        2,
        3,
        4,
        5,
        6,
        2,
        3,
        4,
        0,
        2,
        1,
        6,
        2,
        3,
        4,
        5,
        4,
        6,
        6,
        1,
        2,
        5
    ],
    "platforms": [
        [
            0,
            200,
            1000,
            30
        ],
        [
            0,
            50,
            140,
            20
        ],
        [
            0,
            0,
            20,
            230
        ],
        [
            280,
            100,
            60,
            20
        ],
        [
            650,
            100,
            120,
            20
        ]
    ],
    "spikes": [
        [
            200,
            192,
            700,
            8,
            "u",
            1
        ],
        [
            200,
            192,
            700,
            8,
            "u",
            0
        ]
    ],
    "switches": [
        [
            300,
            90,
            30,
            10,
            1,
            "",
            0,
            0
        ],
        [
            650,
            90,
            30,
            10,
            0,
            "",
            1,
            0
        ],
        [
            900,
            192,
            50,
            10,
            0,
            "LIGHT",
            2,
            1
        ]
    ],
    "gates": [
        [
            120,
            72,
            16,
            128,
            1,
            0,
            ""
        ],
        [
            600,
            0,
            16,
            200,
            0,
            1,
            "EXIT"
        ],
        [
            880,
            0,
            16,
            200,
            0,
            0,
            "LIGHT"
        ]
    ],
    "mirrors": [
        [
            140,
            160,
            20,
            40,
            1,
            0
        ],
        [
            720,
            40,
            24,
            40,
            2,
            22
        ]
    ],
    "monsters": [
        [
            32,
            160,
            2,
            5,
            0,
            132
        ],
        [
            530,
            150,
            3,
            4,
            300,
            550
        ],
        [
            750,
            150,
            3,
            3,
            650,
            880
        ]
    ],
    "exit": [
        960,
        150,
        32,
        50
    ]
},
{
    "name": "Boss",
    "spawn": [
        40,
        30
    ],
    "characterQueue": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0,
        1,
        2,
        3,
        4,
        5,
        6
    ],
    "platforms": [
        [
            0,
            400,
            200,
            30
        ],
        [
            310,
            400,
            200,
            30
        ],
        [
            608,
            400,
            200,
            30
        ],
        [
            0,
            0,
            8,
            400
        ],
        [
            0,
            -20,
            808,
            30
        ],
        [
            800,
            0,
            8,
            400
        ],
        [
            170,
            300,
            170,
            20
        ],
        [
            480,
            300,
            170,
            24
        ],
        [
            8,
            50,
            60,
            20
        ],
        [
            50,
            200,
            120,
            20
        ],
        [
            620,
            200,
            120,
            20
        ],
        [
            320,
            110,
            150,
            20
        ]
    ],
    "spikes": [
        [
            790,
            40,
            8,
            350,
            "l",
            1
        ],
        [
            8,
            80,
            8,
            320,
            "r",
            1
        ]
    ],
    "switches": [],
    "gates": [],
    "mirrors": [
        [
            50,
            360,
            24,
            40,
            1,
            0
        ],
        [
            700,
            360,
            24,
            40,
            1,
            0
        ],
        [
            248,
            256,
            24,
            40,
            2,
            45
        ],
        [
            560,
            256,
            24,
            40,
            2,
            125
        ],
        [
            380,
            70,
            24,
            40,
            1,
            0
        ],
        [
            70,
            70,
            24,
            40,
            3,
            125,
            50,
            180
        ],
        [
            700,
            80,
            24,
            40,
            3,
            0,
            600,
            750
        ],
        [
            380,
            140,
            24,
            40,
            3,
            45,
            320,
            470
        ]
    ],
    "monsters": [
        [
            400,
            200,
            4,
            0,
            0,
            800
        ]
    ],
    "exit": [
        1232,
        168,
        30,
        60
    ]
}],
    loadLevel=index=>{
        localSet('l', index)
        gameState.currentLevelIndex = index;
        const def = LEVEL_DEFS[index];
        gameState.levelData = {
            name: def.name,
            spawn: def.spawn,
            platforms: def.platforms.map(resetXYWH),
            exit: resetXYWH(def.exit),
            characterQueue:def.characterQueue
        };

        gameState.queueIndex = 0;
        gameState.gameComplete = 0;
        gameState.isGameOver = 0;
        gameState.camera = resetXY(0,0);
        gameState.timer = 5.0;
        gameState.bodies = []
        gameState.bs = []
        
        InitUpside()
        
        gameState.spikes = (def.spikes || []).map(([x, y, w, h, dir, theme]) => ({ x, y, w, h, dir, theme }));

        const M = (a, f) => (a || []).map(f);

        gameState.entities = [
            ...(gameState.gates = M(def.gates, ([x, y, w, h, dim = 0, isExit = 0, gt = 0]) => ({
                x, y, w, h, dim, isExit, gt, isOpen: 0, k: 0
            }))),
            ...M(def.switches, ([x, y, w, h, mode = 0, label = 'SW', targetIdx = 0, type = 0]) => ({
                x, y, w, h, mode, label, targetIdx, type, isPressed: 0, k: 1
            })),
            
            ...M(def.mirrors, ([x, y, w, h, type = 1, angle = 0, railMinX = x - 100, railMaxX = x + 100]) => ({
                x, y, w, h, type, angle, railMinX, railMaxX, railY: y, vy: 0, grounded: +(type == 3),
                lightActive: 0, lightTimer: 0, lightDir: 1, lightColor: '#ff0', colorId: 0, k: 2
            })),
            
           ...M(def.monsters, ([x, y, type = 1, color = 0, minX = 0, maxX = 800,
                scale = type == 2 ? 3 : type == 4 ? 4 : type == 3 ? 1.5 : 1.5]) => ({
                x, y, type, 
                color: color , 
                minX, maxX, scale,
                w: (type == 2 ? 15 : type == 3 ? 23 : 29) * scale,
                h: (type == 2 ? 13 : type == 3 ? 31 : 29) * scale,
                vx: 1.5, vy: 0, dir: 1, isDefeated: 0, hitCooldown: 0,
                pauseTimer: 0, shootTimer: 60, jumpTimer: 60, grounded: 0,
                colorTimer: 0, colorIndex: 0,
                remainingColors: type == 4 ? [0, 1, 2, 3, 4, 5, 6] : [],
                k: 3
            }))
        ];

        gameState.bloodParticles = Array.from({ length: 60 }, (_, i) => ({
            x: range(),
            y: range(),
            vy: rand(1) * 1.5 + 0.5,
            vx: rand(.5) * 0.5,
            size: rand(3) + 1,
            color: 5
        }));
        
        resetPlayer(gameState.player,def.spawn[0], def.spawn[1], getCurrentCharacter(gameState.levelData.characterQueue));
    }